name = "SylviaCraft"
author = "Sylviacord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e839045622e5395dfa5b2be143b6aedfb54a07ed871c1bf3e3083559f8d447a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.22"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
