name = "SylviaCraft"
author = "Sylviacord"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0212ef139e51ac4fe94db2423efc006081b852a5be6a6ddd04962bc23aabf6e5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.22"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
